### ISSUE TITLE
when reloading the page while looking at a volume

### ISSUE THREAD

**Issue by whatcoloris** [emergencyindex/emergencyindex.com#28]
the project you're looking at jumps 12 pages ahead!

interesting.... not sure if it's a PROBLEM but it's curious!

**Comment by edwardsharp** [comment]
used to write `window.location.hash` when a project is scrolled into view but writing to `window.location.hash` causes the browser to scroll to that element. so that's been removed to resolve some of those bugz/glitchz. 

anyhow, i'm not able to reproduce this. if i visit https://alveol.us/volume/2012#2012-236-237 and then reload the page, i still end up at the same project... 

can you provide more detail on how this is happening for you?

**Comment by whatcoloris** [comment]
this seems to have disappeared. yay!
